- name: NodeJS | Check if is present
  command: test -x /usr/bin/node
  when: ansible_system == "Linux"
  ignore_errors: yes
  register: node_present

- name: NodeJS | Ensure apt-transport-https is installed.
  apt:
    name: apt-transport-https
    state: present

- name: NodeJS | Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: NodeJS | Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"

- name: NodeJS | Ensure Node.js and npm are installed.
  apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present
    update_cache: yes

- name: NPM | .npmrc
  blockinfile:
    create: yes
    owner: "{{ home_username }}"
    group: "{{ home_usergroup }}"
    path: "{{ home_dir }}/.npmrc"
    block: |
      prefix=~/.npm-packages
